<?php
/* @var $helper Mage_Cms_Helper_Data */
$helper = Mage::helper('cms');
$processor = $helper->getPageTemplateProcessor();
$html = $processor->filter($this->getData('content'));
?>

<p>This is the TypeCMS default template, override this file in your theme or change the template in the config xml. All attributes of the original CMS page and the attributes defined in the config xml are accessible through the <em>$this->getData()</em> method.</p>

<?php echo $html ?>
